import { auth,functions,database } from "./firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { ref,get } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";
import { httpsCallable } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js";
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString("en-GB");
function msg(t,c=""){const e=$("adminMessage");e.textContent=t;e.className=`message-box ${c}`.trim();}
async function requireAdmin(u){return (await get(ref(database,`v2/admins/${u.uid}`))).val()===true;}
function render(data){const x=data.house||{};$("adminHouse").textContent=fmt(x.houseBalance??250000);$("adminProfit").textContent=`${Number(x.houseProfit||0)>=0?"+":""}${fmt(x.houseProfit||0)} 🧪`;$("adminWagered").textContent=`${fmt(x.totalWagered||0)} 🧪`;$("adminPaid").textContent=`${fmt(x.totalPaidOut||0)} 🧪`;$("adminRounds").textContent=fmt(x.rounds||0);$("adminBiggest").textContent=`${fmt(x.biggestPayout||0)} 🧪`;const rows=data.ledger||[];$("casinoLedger").innerHTML=rows.length?rows.map(x=>`<div><span class="ledger-game">${x.game||"casino"}</span><b>${x.username||"Player"}</b><span>Bet ${fmt(x.bet)} 🧪</span><span class="${Number(x.payout||0)>Number(x.bet||0)?"ledger-win":""}">Paid ${fmt(x.payout||0)} 🧪</span><small>${new Date(x.createdAt).toLocaleString()}</small></div>`).join(""):"No development casino activity yet.";}
async function refresh(){try{const r=await httpsCallable(functions,"v3devCasinoAdminSnapshot")({});render(r.data);}catch(e){msg(String(e?.message||"Could not load dev casino").replace(/^FirebaseError:\s*/i,""),"error");}}
async function adjust(direction){const amount=Math.max(1,Math.floor(Number($("houseAmount").value||0)));try{const r=await httpsCallable(functions,"v3devCasinoAdminAdjustHouse")({amount:direction*amount});msg(`DEV House updated: ${fmt(r.data.houseBalance)} test coins.`,"success");await refresh();}catch(e){msg(String(e?.message||"Update failed").replace(/^FirebaseError:\s*/i,""),"error");}}
$("houseAdd").onclick=()=>adjust(1);$("houseRemove").onclick=()=>adjust(-1);$("resetMyDevWallet").onclick=async()=>{try{const r=await httpsCallable(functions,"v3devCasinoResetMyWallet")({});msg(`Your private test wallet is back to ${fmt(r.data.coins)} coins.`,"success");}catch(e){msg(String(e?.message||"Reset failed").replace(/^FirebaseError:\s*/i,""),"error");}};
onAuthStateChanged(auth,async u=>{if(!u){location.href="./index.html";return;}if(!(await requireAdmin(u))){location.href="./hub.html";return;}await refresh();setInterval(refresh,5000);});
