const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { setGlobalOptions } = require("firebase-functions/v2");
const crypto=require("crypto");
setGlobalOptions({region:"europe-west1",maxInstances:5});
const DATABASE_URL="https://bingo-5174e-default-rtdb.europe-west1.firebasedatabase.app";
let adminApp=null;
function services(){
  const { initializeApp }=require("firebase-admin/app");
  const { getDatabaseWithUrl }=require("firebase-admin/database");
  if(!adminApp)adminApp=initializeApp({projectId:"bingo-5174e",databaseURL:DATABASE_URL});
  return {db:getDatabaseWithUrl(DATABASE_URL,adminApp)};
}
const BETS=new Set([10,25,50,100,250,500]);
const START_WALLET=100000,START_HOUSE=250000;
const now=()=>Date.now();
const id=p=>`${p}_${crypto.randomUUID()}`;
const rnd=max=>crypto.randomInt(0,max);
async function access(uid){const {db}=services();const [a,t]=await Promise.all([db.ref(`v2/admins/${uid}`).get(),db.ref(`v3/dev/testers/${uid}`).get()]);return a.val()===true||t.val()===true||t.val()?.enabled===true;}
async function requireAccess(req){if(!req.auth)throw new HttpsError("unauthenticated","Sign in first.");if(!(await access(req.auth.uid)))throw new HttpsError("permission-denied","Private V3 development access required.");return req.auth.uid;}
async function requireAdmin(req){if(!req.auth)throw new HttpsError("unauthenticated","Sign in first.");const {db}=services();if((await db.ref(`v2/admins/${req.auth.uid}`).get()).val()!==true)throw new HttpsError("permission-denied","Admin access required.");return req.auth.uid;}
function bet(v){v=Math.floor(Number(v));if(!BETS.has(v))throw new HttpsError("invalid-argument","Choose a valid test stake.");return v;}
function deck(){const d=[];for(const s of ["S","H","D","C"])for(const r of ["2","3","4","5","6","7","8","9","10","J","Q","K","A"])d.push(`${r}${s}`);for(let i=d.length-1;i>0;i--){const j=rnd(i+1);[d[i],d[j]]=[d[j],d[i]];}return d;}
function value(c){const r=String(c).replace(/[SHDC]$/,'');if(r==="A")return 11;if(["K","Q","J"].includes(r))return 10;return Number(r)||0;}
function hand(cards){let n=cards.reduce((a,c)=>a+value(c),0),aces=cards.filter(c=>c.startsWith("A")).length;while(n>21&&aces){n-=10;aces--;}return n;}
async function ensureWallet(uid){const {db}=services();const r=db.ref(`v3/dev/wallets/${uid}`);await r.transaction(cur=>cur||{coins:START_WALLET,wagered:0,paidOut:0,rounds:0,createdAt:now(),updatedAt:now()});return (await r.get()).val();}
async function ensureHouse(){const {db}=services();const r=db.ref("v3/dev/casino/publicStats");await r.transaction(cur=>cur||{houseBalance:START_HOUSE,houseProfit:0,totalWagered:0,totalPaidOut:0,rounds:0,biggestPayout:0,createdAt:now(),updatedAt:now()});return (await r.get()).val();}
async function economy(uid){const [wallet,house]=await Promise.all([ensureWallet(uid),ensureHouse()]);return {wallet:{coins:wallet.coins},stats:{wagered:wallet.wagered||0,paidOut:wallet.paidOut||0,rounds:wallet.rounds||0},house};}
async function charge(uid,amount){const {db}=services();let fail=false;const r=db.ref(`v3/dev/wallets/${uid}`);const tx=await r.transaction(cur=>{cur=cur||{coins:START_WALLET,wagered:0,paidOut:0,rounds:0};if(Number(cur.coins||0)<amount){fail=true;return;}cur.coins-=amount;cur.wagered=Number(cur.wagered||0)+amount;cur.rounds=Number(cur.rounds||0)+1;cur.updatedAt=now();return cur;});if(!tx.committed||fail)throw new HttpsError("failed-precondition","Not enough TEST COINS. Reset your dev wallet from Casino Control.");await db.ref("v3/dev/casino/publicStats").transaction(cur=>{cur=cur||{houseBalance:START_HOUSE};cur.houseBalance=Number(cur.houseBalance??START_HOUSE)+amount;cur.houseProfit=Number(cur.houseProfit||0)+amount;cur.totalWagered=Number(cur.totalWagered||0)+amount;cur.rounds=Number(cur.rounds||0)+1;cur.updatedAt=now();return cur;});}
async function payout(uid,amount){if(amount<=0)return;const {db}=services();await db.ref(`v3/dev/wallets/${uid}`).transaction(cur=>{cur=cur||{coins:START_WALLET};cur.coins=Number(cur.coins||0)+amount;cur.paidOut=Number(cur.paidOut||0)+amount;cur.updatedAt=now();return cur;});await db.ref("v3/dev/casino/publicStats").transaction(cur=>{cur=cur||{houseBalance:START_HOUSE};cur.houseBalance=Number(cur.houseBalance??START_HOUSE)-amount;cur.houseProfit=Number(cur.houseProfit||0)-amount;cur.totalPaidOut=Number(cur.totalPaidOut||0)+amount;cur.biggestPayout=Math.max(Number(cur.biggestPayout||0),amount);cur.updatedAt=now();return cur;});}
async function username(uid){const {db}=services();return (await db.ref(`v2/profiles/${uid}/username`).get()).val()||"Tester";}
async function ledger(uid,data){const {db}=services();await db.ref("v3/dev/casino/ledger").push({...data,uid,username:await username(uid),createdAt:now()});}
function bjPublic(s){const resolved=s.state!=="active";return {state:s.state,outcome:s.outcome||null,bet:s.bet,playerCards:s.playerCards||[],dealerCards:resolved?s.dealerCards:[s.dealerCards[0],"BACK"],dealerHidden:!resolved,playerScore:hand(s.playerCards||[]),dealerScore:resolved?hand(s.dealerCards||[]):null,canDouble:s.state==="active"&&s.playerCards.length===2&&!s.doubled,message:s.message||""};}
function dealerResolve(s){while(hand(s.dealerCards)<17)s.dealerCards.push(s.deck.shift());const p=hand(s.playerCards),d=hand(s.dealerCards);if(d>21||p>d){s.outcome="win";s.payout=s.bet*2;s.message=d>21?`General Sassy busts on ${d}. TEST WIN: ${s.payout}.`:`${p} beats ${d}. TEST WIN: ${s.payout}.`;}else if(p===d){s.outcome="push";s.payout=s.bet;s.message=`Push on ${p}. Test stake returned.`;}else{s.outcome="loss";s.payout=0;s.message=`General Sassy wins ${d} to ${p}. Dev House takes it.`;}s.state="resolved";return s;}
exports.v3devCasinoEnsure=onCall(async req=>{const uid=await requireAccess(req);return await economy(uid);});
exports.v3devCasinoBlackjackStart=onCall(async req=>{const uid=await requireAccess(req),stake=bet(req.data?.bet),{db}=services(),r=db.ref(`v3/dev/casino/blackjack/${uid}`),d=deck(),sid=id("bj");const existing=(await r.get()).val();if(existing?.state==="active")throw new HttpsError("failed-precondition","Finish the current DEV Blackjack hand first.");await charge(uid,stake);let s={id:sid,state:"active",bet:stake,deck:d,playerCards:[d.shift(),d.shift()],dealerCards:[d.shift(),d.shift()],doubled:false,createdAt:now(),message:"Your move."};const p=hand(s.playerCards),dv=hand(s.dealerCards);if(p===21||dv===21){s.state="resolved";if(p===21&&dv===21){s.outcome="push";s.payout=stake;s.message="Double Blackjack. Test stake returned.";}else if(p===21){s.outcome="win";s.payout=Math.floor(stake*2.5);s.message=`Natural Blackjack! TEST payout ${s.payout}.`;}else{s.outcome="loss";s.payout=0;s.message="General Sassy has Blackjack. Dev tragedy.";}await payout(uid,s.payout);await ledger(uid,{game:"blackjack",bet:stake,payout:s.payout,outcome:s.outcome});}await r.set(s);return {...bjPublic(s),economy:await economy(uid)};});
exports.v3devCasinoBlackjackAction=onCall(async req=>{const uid=await requireAccess(req),action=String(req.data?.action||""),{db}=services(),r=db.ref(`v3/dev/casino/blackjack/${uid}`);if(!["hit","stand","double"].includes(action))throw new HttpsError("invalid-argument","Unknown action.");let s=(await r.get()).val();if(!s||s.state!=="active")throw new HttpsError("failed-precondition","No active DEV Blackjack hand.");if(action==="double"){if(s.playerCards.length!==2||s.doubled)throw new HttpsError("failed-precondition","Double is only available on the opening hand.");await charge(uid,s.bet);s.bet*=2;s.doubled=true;s.playerCards.push(s.deck.shift());if(hand(s.playerCards)>21){s.state="resolved";s.outcome="loss";s.payout=0;s.message=`Bust on ${hand(s.playerCards)}. Dev House says thank you.`;}else dealerResolve(s);}else if(action==="hit"){s.playerCards.push(s.deck.shift());if(hand(s.playerCards)>21){s.state="resolved";s.outcome="loss";s.payout=0;s.message=`Bust on ${hand(s.playerCards)}. Dev House says thank you.`;}else s.message="Hit or stand?";}else dealerResolve(s);if(s.state==="resolved"){await payout(uid,s.payout||0);await ledger(uid,{game:"blackjack",bet:s.bet,payout:s.payout||0,outcome:s.outcome});}await r.set(s);return {...bjPublic(s),economy:await economy(uid)};});
exports.v3devCasinoHigherLowerStart=onCall(async req=>{const uid=await requireAccess(req),stake=bet(req.data?.bet),{db}=services(),r=db.ref(`v3/dev/casino/higherLower/${uid}`),d=deck();const cur=(await r.get()).val();if(cur?.state==="active")throw new HttpsError("failed-precondition","Finish the current DEV Higher/Lower round first.");await charge(uid,stake);const s={id:id("hl"),state:"active",bet:stake,currentCard:d.shift(),deck:d,createdAt:now(),message:"Higher or lower?"};await r.set(s);return {...s,deck:undefined,economy:await economy(uid)};});
exports.v3devCasinoHigherLowerGuess=onCall(async req=>{const uid=await requireAccess(req),guess=String(req.data?.guess||""),{db}=services(),r=db.ref(`v3/dev/casino/higherLower/${uid}`);if(!["higher","lower"].includes(guess))throw new HttpsError("invalid-argument","Choose higher or lower.");let s=(await r.get()).val();if(!s||s.state!=="active")throw new HttpsError("failed-precondition","No active DEV Higher/Lower round.");const next=s.deck.shift(),a=value(s.currentCard),b=value(next);let outcome,pay;if(a===b){outcome="push";pay=s.bet;}else if((guess==="higher"&&b>a)||(guess==="lower"&&b<a)){outcome="win";pay=s.bet*2;}else{outcome="loss";pay=0;}s.state="resolved";s.outcome=outcome;s.nextCard=next;s.payout=pay;s.message=outcome==="win"?`Correct! TEST payout ${pay}.`:outcome==="push"?"Same rank — test stake returned.":"Wrong. The Dev House pockets it.";await payout(uid,pay);await ledger(uid,{game:"higher-lower",bet:s.bet,payout:pay,outcome});await r.set(s);return {...s,deck:undefined,economy:await economy(uid)};});
const SYMBOLS=[{s:"🍒",w:34,m:4},{s:"🔔",w:25,m:7},{s:"💎",w:18,m:12},{s:"7️⃣",w:12,m:25},{s:"👑",w:8,m:50},{s:"🎖️",w:3,m:125}];
function spinSymbol(){const total=SYMBOLS.reduce((n,x)=>n+x.w,0);let n=rnd(total);for(const x of SYMBOLS){if(n<x.w)return x.s;n-=x.w;}return SYMBOLS[0].s;}
exports.v3devCasinoSlotsSpin=onCall(async req=>{const uid=await requireAccess(req),stake=bet(req.data?.bet);await charge(uid,stake);const reels=[spinSymbol(),spinSymbol(),spinSymbol()];let mult=0;if(reels[0]===reels[1]&&reels[1]===reels[2])mult=SYMBOLS.find(x=>x.s===reels[0])?.m||0;else if(reels[0]===reels[1]||reels[1]===reels[2]||reels[0]===reels[2])mult=1;const pay=stake*mult,outcome=pay>stake?"win":pay===stake?"push":"loss";await payout(uid,pay);const message=outcome==="win"?`${mult}× DEV WIN — ${pay.toLocaleString("en-GB")} test coins!`:outcome==="push"?"Pair! Test stake returned.":"No match. General Sassy pockets the test stake.";await ledger(uid,{game:"slots",bet:stake,payout:pay,outcome,reels:reels.join(" ")});return {ok:true,bet:stake,reels,multiplier:mult,payout:pay,outcome,message,economy:await economy(uid)};});
exports.v3devCasinoAdminAdjustHouse=onCall(async req=>{await requireAdmin(req);const amount=Math.trunc(Number(req.data?.amount||0));if(!Number.isFinite(amount)||amount===0||Math.abs(amount)>10000000)throw new HttpsError("invalid-argument","Choose a valid adjustment.");const {db}=services();let balance=0;await db.ref("v3/dev/casino/publicStats").transaction(cur=>{cur=cur||{houseBalance:START_HOUSE};balance=Math.max(0,Number(cur.houseBalance??START_HOUSE)+amount);cur.houseBalance=balance;cur.updatedAt=now();return cur;});return {ok:true,houseBalance:balance};});
exports.v3devCasinoAdminSnapshot=onCall(async req=>{await requireAdmin(req);const {db}=services();const [h,l]=await Promise.all([ensureHouse(),db.ref("v3/dev/casino/ledger").get()]);const ledgerRows=Object.values(l.val()||{}).sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0)).slice(0,50);return {house:h,ledger:ledgerRows};});
exports.v3devCasinoResetMyWallet=onCall(async req=>{const uid=await requireAccess(req);const {db}=services();await db.ref(`v3/dev/wallets/${uid}`).set({coins:START_WALLET,wagered:0,paidOut:0,rounds:0,createdAt:now(),updatedAt:now()});await db.ref(`v3/dev/casino/blackjack/${uid}`).remove();await db.ref(`v3/dev/casino/higherLower/${uid}`).remove();return {ok:true,coins:START_WALLET};});
